### ISSUE TITLE
multiple warnings will occur if rake files have constant variables.

### ISSUE THREAD

**Issue by oakbow** [willnet/rake_shared_context#22]
because this shared context use before block, it cause multiple warnings when I define constant variables in rake files.

```
/lib/tasks/foo_bar.rake:3: warning: already initialized constant FOO_BAR
/lib/tasks/foo_bar.rake:3: warning: previous definition of FOO_BAR was here
/lib/tasks/foo_bar.rake:4: warning: already initialized constant HOO_BAR
/lib/tasks/foo_bar.rake:4: warning: previous definition of HOO_BAR was here
  :
```

I guess the reason is multiple requiring those rake files caused by before(:each) block.
I tried to change it to before(:all), but it didi't work.
I will be glad if you fix this problem, thanks.

**Comment by willnet** [comment]
@oakbow 

I created `fix-load-twice` branch to fix this issue. It load rake tasks once before spec run.
You can use it now but it maybe not work with multi-thread environment or spring.
I gonna write tests for them but I don't know when they are finished. I would be happy If you write tests or another solution.
